ALTER TYPE "AssignmentActivityType" ADD VALUE IF NOT EXISTS 'INVITATION_CREATED';
ALTER TYPE "AssignmentActivityType" ADD VALUE IF NOT EXISTS 'INVITATION_ACCEPTED';
ALTER TYPE "AssignmentActivityType" ADD VALUE IF NOT EXISTS 'INVITATION_DECLINED';
ALTER TYPE "AssignmentActivityType" ADD VALUE IF NOT EXISTS 'REPLACEMENT_SELECTED';
