export const APP_NAME = "PPAM Planificador";

export const AUTH_ROUTES = ["/login", "/forgot-password", "/reset-password"];

export const DEFAULT_CONFIRMATION_LEAD_DAYS = 8;
export const DEFAULT_REMINDER_TIMING_DAYS = [5, 1] as const;
export const DEFAULT_FINAL_REMINDER_HOURS = 3;
export const DEFAULT_PRIMARY_RESPONSE_TIMEOUT_HOURS = 48;
export const DEFAULT_PRIMARY_REMINDER_OFFSETS_HOURS = [12, 24, 40] as const;
export const DEFAULT_URGENT_PRIMARY_RESPONSE_TIMEOUT_HOURS = 12;
export const DEFAULT_URGENT_PRIMARY_REMINDER_OFFSETS_HOURS = [4, 8] as const;
export const DEFAULT_URGENT_THRESHOLD_HOURS = 72;
export const DEFAULT_REPLACEMENT_RESPONSE_TIMEOUT_HOURS = 12;
export const DEFAULT_REPLACEMENT_REMINDER_OFFSETS_HOURS = [4, 8] as const;
export const DEFAULT_URGENT_REPLACEMENT_RESPONSE_TIMEOUT_HOURS = 4;
export const DEFAULT_URGENT_REPLACEMENT_REMINDER_OFFSETS_HOURS = [2] as const;
export const DEFAULT_CENSUS_RESPONSE_TIMEOUT_HOURS = 72;
export const DEFAULT_CENSUS_REMINDER_OFFSETS_HOURS = [24, 48] as const;
export const DEFAULT_ADMIN_ALERT_EMAIL = "admin@ppam.local";
